# Generated by Django 3.0.7 on 2020-06-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_growth_app', '0003_auto_20200604_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='username'),
        ),
    ]
