# Generated by Django 3.0.7 on 2020-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_growth_app', '0004_auto_20200604_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_users_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_users_count',
            field=models.IntegerField(default=0),
        ),
    ]
