# Generated by Django 3.0.7 on 2020-06-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_growth_app', '0006_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_info', models.TextField(default='Your profile info')),
            ],
        ),
    ]
