# Generated by Django 3.0.7 on 2020-06-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viral_growth_app', '0008_user_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(upload_to=None)),
                ('page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viral_growth_app.Page')),
            ],
        ),
    ]
